"""
Tool for persisting images generated by agents.
"""

import uuid
from pathlib import Path
from PIL import Image
from smolagents import Tool

class PersistentImageTool(Tool):
    name = "save_and_get_image_url"
    description = "Saves a PIL Image object and returns its public URL path. Use this to get a link for Markdown."
    inputs = {
        "image": {
            "type": "any",
            "description": "The PIL.Image object to save."
        }
    }
    output_type = "string"

    def __init__(self, image_dir: str = "static/images"):
        super().__init__()
        self.image_dir = Path(image_dir)
        self.image_dir.mkdir(parents=True, exist_ok=True)

    def forward(self, image: any) -> str:
        # Resiliency: If sub-agent returned a dict or list, search for the image object inside it
        pil_image = None
        if isinstance(image, Image.Image):
            pil_image = image
        elif isinstance(image, dict):
            for v in image.values():
                if isinstance(v, Image.Image):
                    pil_image = v
                    break
        elif isinstance(image, (list, tuple)):
            for v in image:
                if isinstance(v, Image.Image):
                    pil_image = v
                    break

        if not pil_image:
            return "Error: Could not find a PIL Image object in the input."
        
        filename = f"{uuid.uuid4()}.png"
        filepath = self.image_dir / filename
        pil_image.save(filepath)
        return f"/static/images/{filename}"

def load_persist_tool(image_dir: str = "static/images"):
    return PersistentImageTool(image_dir=image_dir)
